### ISSUE TITLE
[feature] Email notifications.

### ISSUE THREAD

**Issue by postmodern** [rubygems/gem-testers#22]
It might be handy to enable Email notifications of failures, sending them to the email addresses in `Gem::Specification`.

**Comment by erikh** [comment]
Definitely something we'd like to do, but this requires a bit more infrastructure than we have now (mail queueing is hard, let's go shopping).

This is gonna take a while; there are RSS feeds until then, but leaving this open.

**Comment by postmodern** [comment]
Could we get RSS feeds grouped by author? This way I could watch over all my gems.

**Comment by erikh** [comment]
author support is going to take a little extra sauce, and we're not quite there yet, since we don't actually process gems.

**Comment by sonalkr132** [comment]
This repo is not in use and being archived.
