### ISSUE TITLE
Handling YAML 1.1 from the clients

### ISSUE THREAD

**Issue by erikh** [rubygems/gem-testers#26]
JRuby 1.6 outputs YAML 1.1 which is giving our create action in test_results hives.

https://github.com/rubygems/rubygems-test/issues/#issue/30

**Comment by capoferro** [comment]
Looks like we need to get Engine Yard to install Ruby with Psych. This works fine locally with Psych available.

**Comment by erikh** [comment]
I need to verify this is still an issue at EY.

**Comment by sonalkr132** [comment]
This repo is not in use and being archived.
