### ISSUE TITLE
Does the x86_64 arch make sense for the jruby platform?

### ISSUE THREAD

**Issue by erikh** [rubygems/gem-testers#5]
If I'm looking at jruby, does it matter that it's x86_64? If I'm looking at x86_64, does it matter that I might see jruby reports mixed in with matz's ruby? I don't think anyone thoughtful and reasonable will be confused; it's more a matter of the UI showing irrelevant or less-than-useful info.

Original: https://github.com/bluepojo/gem-testers/issues#issue/13

**Comment by postmodern** [comment]
Yes, especially for testing FFI bindings on various OSes/Platforms.

**Comment by erikh** [comment]
Good point. I'll close this one.
