### ISSUE TITLE
JSON responders

### ISSUE THREAD

**Issue by dominikh** [rubygems/gem-testers#8]
Here a summary of the information I need for the bot, as discussed in IRC:
- add `total_successes` and `total_fails` fields to each individual
  version reported in the per-gem JSON responders. Those should not be
  affected by the limit on individual reports in the JSON
- provide a global JSON stream with the latest reports (optimally
  always for a specific time frame, e.g. the last hour; maybe capped
  to X reports if the report counts get too high)
  - the global JSON should not only contain the links to the reports,
    but also directly inline the most important information, i.e. gem
    name, version, interpreter/architecture, success/fail. The
    complete output of the test is _not_ needed.

**Comment by capoferro** [comment]
Part 2: 39f9ab148b5103ec3a3d3592214e74535ffaac32

Part 1: pending

**Comment by dominikh** [comment]
The individual test results in the global JSON do not contain the gem names. Can that be added?

**Comment by capoferro** [comment]
Next release has pass_count and fail_count for /gems/:name/v/:number.json
